// lib/services/pdf_service.dart
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfService {
  // --------------------------------------------------------------
  // 🧪 1. AI CHECKUP REPORT (Your original function)
  // --------------------------------------------------------------
  static Future<void> generateCheckupReport({
    required String patientName,
    required String dateTime,
    required String symptom,
    required String diagnosis,
    required String lang,
  }) async {
    final pdf = pw.Document();
    final font = await PdfGoogleFonts.nunitoRegular();
    final bold = await PdfGoogleFonts.nunitoBold();

    // Labels
    final isHindi = lang == 'hi';
    final isMarathi = lang == 'mr';

    final title = isHindi
        ? 'स्वास्थ्य तपासणी अहवाल'
        : isMarathi
            ? 'आरोग्य तपासणी अहवाल'
            : 'Health Checkup Report';

    final patientLabel = isHindi
        ? 'रुग्णाचे नाव:'
        : isMarathi
            ? 'रुग्णाचे नाव:'
            : 'Patient Name:';

    final dateLabel = isHindi
        ? 'तारीख:'
        : isMarathi
            ? 'तारीख:'
            : 'Date:';

    final symptomLabel = isHindi
        ? 'लक्षणे:'
        : isMarathi
            ? 'लक्षणे:'
            : 'Symptoms:';

    final diagnosisLabel = isHindi
        ? 'तपासणी निकाल:'
        : isMarathi
            ? 'तपासणी निकाल:'
            : 'Diagnosis Result:';

    final footerNote = isHindi
        ? 'आपल्या आरोग्याची काळजी घ्या — आपला डिजिटल आरोग्य सहाय्यक, आयूट्रॅक'
        : isMarathi
            ? 'आपल्या आरोग्याची काळजी घ्या — आपला डिजिटल आरोग्य सहकारी, आयूट्रॅक'
            : 'Take care of your health — Your Digital Health Partner, AayuTrack';

    // PDF Page
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => [
          // Header
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(title,
                      style: pw.TextStyle(
                          font: bold, fontSize: 22, color: PdfColors.teal800)),
                  pw.Text("Generated by AayuTrack",
                      style: pw.TextStyle(
                          font: font, fontSize: 12, color: PdfColors.grey600)),
                ],
              ),
              pw.Container(
                width: 50,
                height: 50,
                decoration: const pw.BoxDecoration(
                  color: PdfColors.teal,
                  shape: pw.BoxShape.circle,
                ),
                child: pw.Center(
                  child: pw.Text("A",
                      style: pw.TextStyle(
                          font: bold, fontSize: 28, color: PdfColors.white)),
                ),
              )
            ],
          ),
          pw.SizedBox(height: 20),
          pw.Divider(),

          // Patient details
          pw.Text("$patientLabel $patientName",
              style: pw.TextStyle(font: bold, fontSize: 14)),
          pw.Text("$dateLabel $dateTime",
              style: pw.TextStyle(font: font, fontSize: 12)),
          pw.SizedBox(height: 20),

          // Symptom
          pw.Text(symptomLabel,
              style: pw.TextStyle(
                  font: bold, fontSize: 14, color: PdfColors.teal800)),
          pw.Container(
              padding: const pw.EdgeInsets.all(10),
              margin: const pw.EdgeInsets.only(top: 8, bottom: 16),
              decoration: pw.BoxDecoration(
                  color: PdfColors.grey200,
                  borderRadius: pw.BorderRadius.circular(8)),
              child: pw.Text(symptom, style: pw.TextStyle(font: font))),

          // Diagnosis
          pw.Text(diagnosisLabel,
              style: pw.TextStyle(
                  font: bold, fontSize: 14, color: PdfColors.teal800)),
          pw.Container(
              padding: const pw.EdgeInsets.all(10),
              margin: const pw.EdgeInsets.only(top: 8, bottom: 20),
              decoration: pw.BoxDecoration(
                  color: PdfColors.grey100,
                  borderRadius: pw.BorderRadius.circular(8)),
              child: pw.Text(diagnosis,
                  style: pw.TextStyle(font: font, fontSize: 12))),

          pw.Divider(),
          pw.Center(
            child: pw.Text(footerNote,
                style: pw.TextStyle(
                    font: bold, color: PdfColors.teal800, fontSize: 12)),
          ),
          pw.Center(
            child: pw.Text(
              "AayuTrack © ${DateTime.now().year}",
              style: pw.TextStyle(font: font, fontSize: 10),
            ),
          ),
        ],
      ),
    );

    // Save & Share
    final file = await _savePdf(
        pdf, "AayuTrack_Checkup_${DateTime.now().millisecondsSinceEpoch}.pdf");

    _share(file);
  }

  // --------------------------------------------------------------
  // 📝 2. DASHBOARD DAILY REPORT (NEW FUNCTION YOU NEED)
  // --------------------------------------------------------------
  static Future<void> generateReport({
    required int steps,
    required int heartRate,
    required int hydration,
  }) async {
    final pdf = pw.Document();
    final font = await PdfGoogleFonts.nunitoRegular();
    final bold = await PdfGoogleFonts.nunitoBold();

    final now = DateFormat.yMMMMd().add_jm().format(DateTime.now());

    pdf.addPage(
      pw.Page(
        margin: const pw.EdgeInsets.all(32),
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text("AayuTrack Daily Health Summary",
                style: pw.TextStyle(
                    font: bold, fontSize: 22, color: PdfColors.teal800)),
            pw.SizedBox(height: 6),
            pw.Text("Generated on $now",
                style: pw.TextStyle(
                    font: font, fontSize: 12, color: PdfColors.grey600)),
            pw.Divider(height: 32),
            pw.Text("Today's Stats",
                style: pw.TextStyle(
                    font: bold, color: PdfColors.teal800, fontSize: 16)),
            pw.SizedBox(height: 10),
            _row("Steps", "$steps steps", font),
            _row("Heart Rate", "$heartRate bpm", font),
            _row("Hydration", "$hydration ml", font),
            pw.SizedBox(height: 20),
            pw.Divider(),
            pw.Center(
              child: pw.Text("AayuTrack — Stay Consistent, Stay Healthy",
                  style: pw.TextStyle(
                      font: bold, fontSize: 12, color: PdfColors.teal700)),
            )
          ],
        ),
      ),
    );

    final file = await _savePdf(pdf,
        "AayuTrack_Dashboard_${DateTime.now().millisecondsSinceEpoch}.pdf");

    _share(file);
  }

  // Row builder
  static pw.Widget _row(String label, String value, pw.Font font) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: pw.TextStyle(font: font, fontSize: 14)),
          pw.Text(value,
              style: pw.TextStyle(
                  font: font, fontSize: 14, color: PdfColors.teal800)),
        ],
      ),
    );
  }

  // --------------------------------------------------------------
  // 📥 Save & Share Helpers
  // --------------------------------------------------------------
  static Future<File> _savePdf(pw.Document pdf, String name) async {
    final dir = await _getDownloadDirectory();
    final file = File("${dir.path}/$name");
    await file.writeAsBytes(await pdf.save());
    debugPrint("📄 PDF saved: ${file.path}");
    return file;
  }

  static void _share(File file) async {
    if (!kIsWeb) {
      await Share.shareXFiles([XFile(file.path)]);
    } else {
      await Printing.sharePdf(
          bytes: await file.readAsBytes(), filename: file.path);
    }
  }

  static Future<Directory> _getDownloadDirectory() async {
    if (Platform.isAndroid || Platform.isWindows) {
      final dir = Directory('/storage/emulated/0/Download');
      if (await dir.exists()) return dir;
      return await getApplicationDocumentsDirectory();
    }
    return await getApplicationDocumentsDirectory();
  }
}
