// lib/services/pdf_service.dart
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

/// 📑 PdfService — professional, multilingual health report generator.
class PdfService {
  /// Generate a detailed AI Checkup report
  static Future<void> generateCheckupReport({
    required String patientName,
    required String dateTime,
    required String symptom,
    required String diagnosis,
    required String lang,
  }) async {
    final pdf = pw.Document();

    // Fonts
    final font = await PdfGoogleFonts.nunitoRegular();
    final boldFont = await PdfGoogleFonts.nunitoBold();

    // Language-based labels
    final isHindi = lang == 'hi';
    final isMarathi = lang == 'mr';

    final title = isHindi
        ? 'स्वास्थ्य तपासणी अहवाल'
        : isMarathi
        ? 'आरोग्य तपासणी अहवाल'
        : 'Health Checkup Report';

    final patientLabel = isHindi
        ? 'रुग्णाचे नाव:'
        : isMarathi
        ? 'रुग्णाचे नाव:'
        : 'Patient Name:';

    final dateLabel = isHindi
        ? 'तारीख:'
        : isMarathi
        ? 'तारीख:'
        : 'Date:';

    final symptomLabel = isHindi
        ? 'लक्षणे:'
        : isMarathi
        ? 'लक्षणे:'
        : 'Symptoms:';

    final diagnosisLabel = isHindi
        ? 'तपासणी निकाल:'
        : isMarathi
        ? 'तपासणी निकाल:'
        : 'Diagnosis Result:';

    final footerNote = isHindi
        ? 'आपल्या आरोग्याची काळजी घ्या — आपला डिजिटल आरोग्य सहाय्यक, आयूट्रॅक'
        : isMarathi
        ? 'आपल्या आरोग्याची काळजी घ्या — आपला डिजिटल आरोग्य सहकारी, आयूट्रॅक'
        : 'Take care of your health — Your Digital Health Partner, AayuTrack';

    // ✅ Create Page
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4.copyWith(
          marginLeft: 32,
          marginRight: 32,
          marginTop: 40,
          marginBottom: 40,
        ),
        build: (context) => [
          // HEADER
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    title,
                    style: pw.TextStyle(
                      font: boldFont,
                      fontSize: 22,
                      color: PdfColors.teal800,
                    ),
                  ),
                  pw.SizedBox(height: 6),
                  pw.Text(
                    'Generated by AayuTrack',
                    style: pw.TextStyle(
                      font: font,
                      fontSize: 12,
                      color: PdfColors.grey600,
                    ),
                  ),
                ],
              ),
              pw.Container(
                width: 50,
                height: 50,
                decoration: const pw.BoxDecoration(
                  color: PdfColors.teal,
                  shape: pw.BoxShape.circle,
                ),
                child: pw.Center(
                  child: pw.Text(
                    'A',
                    style: pw.TextStyle(
                      font: boldFont,
                      fontSize: 28,
                      color: PdfColors.white,
                    ),
                  ),
                ),
              ),
            ],
          ),
          pw.SizedBox(height: 20),
          pw.Divider(color: PdfColors.teal200, thickness: 1),
          pw.SizedBox(height: 18),

          // PATIENT DETAILS
          pw.Text(
            '$patientLabel $patientName',
            style: pw.TextStyle(font: boldFont, fontSize: 14),
          ),
          pw.Text(
            '$dateLabel $dateTime',
            style: pw.TextStyle(font: font, fontSize: 12),
          ),
          pw.SizedBox(height: 18),

          // SYMPTOMS
          pw.Text(
            symptomLabel,
            style: pw.TextStyle(
              font: boldFont,
              fontSize: 14,
              color: PdfColors.teal800,
            ),
          ),
          pw.Container(
            padding: const pw.EdgeInsets.all(10),
            margin: const pw.EdgeInsets.only(top: 6, bottom: 14),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey200,
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Text(symptom, style: pw.TextStyle(font: font)),
          ),

          // DIAGNOSIS
          pw.Text(
            diagnosisLabel,
            style: pw.TextStyle(
              font: boldFont,
              fontSize: 14,
              color: PdfColors.teal800,
            ),
          ),
          pw.Container(
            padding: const pw.EdgeInsets.all(10),
            margin: const pw.EdgeInsets.only(top: 6, bottom: 20),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Text(
              diagnosis,
              style: pw.TextStyle(font: font, fontSize: 12),
            ),
          ),

          // FOOTER
          pw.Divider(),
          pw.SizedBox(height: 10),
          pw.Center(
            child: pw.Text(
              footerNote,
              textAlign: pw.TextAlign.center,
              style: pw.TextStyle(
                font: boldFont,
                fontSize: 12,
                color: PdfColors.teal800,
              ),
            ),
          ),
          pw.SizedBox(height: 10),
          pw.Center(
            child: pw.Text(
              'AayuTrack © ${DateFormat.y().format(DateTime.now())}',
              style: pw.TextStyle(
                font: font,
                fontSize: 10,
                color: PdfColors.grey600,
              ),
            ),
          ),
        ],
        footer: (context) => pw.Align(
          alignment: pw.Alignment.centerRight,
          child: pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: pw.TextStyle(font: font, fontSize: 10),
          ),
        ),
      ),
    );

    // SAVE FILE
    final fileName =
        'AayuTrack_Report_${DateFormat('yyyyMMdd_HHmmss').format(DateTime.now())}.pdf';
    final dir = await _getDownloadDirectory();
    final filePath = '${dir.path}/$fileName';
    final file = File(filePath);
    await file.writeAsBytes(await pdf.save());

    if (!kIsWeb) {
      await Share.shareXFiles([XFile(filePath)]);
    } else {
      await Printing.sharePdf(bytes: await pdf.save(), filename: fileName);
    }

    debugPrint('✅ PDF successfully generated at: $filePath');
  }

  /// 📂 Finds the correct save directory (Android/Windows/iOS/Web)
  static Future<Directory> _getDownloadDirectory() async {
    if (Platform.isAndroid || Platform.isWindows) {
      final dir = Directory('/storage/emulated/0/Download');
      if (await dir.exists()) return dir;
      return await getApplicationDocumentsDirectory();
    }
    return await getApplicationDocumentsDirectory();
  }

  /// Quick default generator for Dashboard
  static Future<void> generateAndSharePdf() async {
    final now = DateFormat.yMMMd().add_jm().format(DateTime.now());
    await generateCheckupReport(
      patientName: 'User',
      dateTime: now,
      symptom: 'General wellness summary',
      diagnosis: 'All vitals appear stable. Maintain hydration and exercise!',
      lang: 'en',
    );
  }
}
